DATA_BLOCK "DB_Elevador_Interface"
{ S7_Optimized_Access := 'FALSE' }
VERSION : 0.1
   VAR 
      BP1 : Bool;   // Boton subir
      BP2 : Bool;   // Boton bajar
      LS1 : Bool;   // Limite inferior (cocina)
      LS2 : Bool;   // Limite superior (servicio)
      MC1 : Bool;   // Contactor subida
      MC2 : Bool;   // Contactor bajada
      L1 : Bool;    // Lampara piso inferior
      L2 : Bool;    // Lampara piso superior
   END_VAR

BEGIN
END_DATA_BLOCK
